app = 'bandpass'
primary_region = 'sjc'

[build]

[env]
  ENABLE_AUDIO_ANALYSIS = "true"
  ANALYZER_CONCURRENCY = "4"

[processes]
  web = "node server.js"
  worker = "node worker/main.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ["web"]

[[vm]]
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 4
  processes = ["worker"]
